name: Run CI checks

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Just
        uses: extractions/setup-just@v2
        with:
          just-version: 1.25.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.8

      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: 1.8.2

      - uses: actions/cache@v4.0.2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Run linters
        run: just lint

      - name: Run unit tests
        run: just test
